language: erlang
otp_release:
        - 18.2.1
        - 18.1
        - 18.0
        - 17.5
        - R15B
notifications:
        on_success: always
        on_failure: always
        on_start: always
        webhooks: 'https://aqueous-fortress-79036.herokuapp.com/travisci/hooks'
